### ISSUE TITLE
Installing “terminal-fusion@2.4.2” failed...

### ISSUE THREAD

**Issue by emveeoh** [fusion809/terminal-fusion#5]
**MY CONFIG:**
- Atom    : 1.12.5
- Electron: 1.3.9
- Chrome  : 52.0.2743.82
- Node    : 6.5.0
- apm  1.12.9
- npm  3.10.5
- node 4.4.5
- python 2.7.12
- git 2.7.4
- OS Linux Mint 18 Cinnamon (4.4.0-47-generic)

**INSTALLATION ERROR MESSAGE FROM ATOM:**

```
Installing “terminal-fusion@2.4.2” failed...

> pty.js@0.3.1 install /tmp/apm-install-dir-1161022-14825-137mzne/node_modules/terminal-fusion/node_modules/pty.js
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-1161022-14825-137mzne/node_modules/terminal-fusion/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
pty.target.mk:94: recipe for target 'Release/obj.target/pty/src/unix/pty.o' failed
make: Leaving directory '/tmp/apm-install-dir-1161022-14825-137mzne/node_modules/terminal-fusion/node_modules/pty.js/build'
/tmp/apm-install-dir-1161022-14825-137mzne
└── (empty)


make: g++: Command not found
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-47-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-1161022-14825-137mzne/node_modules/terminal-fusion/node_modules/pty.js
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-1161022-14825-137mzne/package.json'
npm WARN apm-install-dir-1161022-14825-137mzne No description
npm WARN apm-install-dir-1161022-14825-137mzne No repository field.
npm WARN apm-install-dir-1161022-14825-137mzne No README data
npm WARN apm-install-dir-1161022-14825-137mzne No license field.
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/mvo/.atom/.apm/.apmrc" "--userconfig" "/home/mvo/.atom/.apmrc" "install" "/tmp/d-1161022-14825-5g2lpy/package.tgz" "--runtime=electron" "--target=1.3.9" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-1161022-14825-137mzne/npm-debug.log
npm ERR! code 1
```

**npm-debug.log was not created and, therefore not available to include in this support request.**

**Comment by fusion809** [comment]
Ah what about this error is mysterious buddy? 

> make: g++: Command not found

That says it all. You need to install `g++`, or if you would prefer `build-essential`. If you would like a one-liner to install it:

```bash
sudo apt-get install -y build-essential
```

will do it. Then it should work just fine.

**Comment by fusion809** [comment]
I decided to add this information to this repo's README, as I doubt you'll be the only one to get this error.

**Comment by emveeoh** [comment]
Works! Thank you very much for the help! :)
